module.exports = {
    "Ironman 70.3 Lake Stevens": [{
        name: "Ironman 70.3 Lake Stevens",
        eventId: 27485,
        courseId: 0,
        pages: 4,
        year: 2006,
        type: 1,
    }, {
        name: "Ironman 70.3 Lake Stevens",
        eventId: 29490,
        courseId: 0,
        pages: 8,
        year: 2007,
        type: 1,
    }, {
        name: "Ironman 70.3 Lake Stevens",
        eventId: 60533,
        courseId: 0,
        pages: 9,
        year: 2008,
        type: 1,
    }, {
        name: "Ironman 70.3 Lake Stevens",
        eventId: 61082,
        courseId: 0,
        pages: 9,
        year: 2009,
        type: 1,
    }, {
        name: "Ironman 70.3 Lake Stevens",
        eventId: 116000,
        courseId: 0,
        pages: 11,
        year: 2010,
        type: 1,
    }, {
        name: "Ironman 70.3 Lake Stevens",
        eventId: 151052,
        courseId: 0,
        pages: 10,
        year: 2011,
        type: 1,
    }, {
        name: "Ironman 70.3 Lake Stevens",
        eventId: 219124,
        courseId: 0,
        pages: 9,
        year: 2012,
        type: 1,
        scraperName: 'without_time',
    }, {
        name: "Ironman 70.3 Lake Stevens",
        eventId: 243758,
        courseId: 0,
        pages: 12,
        year: 2013,
        type: 1,
        scraperName: 'without_time',
    }]
};
