var raceNames =  [ "Ironman Florida"
                    // "Ironman Arizona",
                    // "Ironman Cozumel",
                    // "Ironman Western Australia",
                    // "Ironman New Zealand",
                    // "Ironman Asia-Pacific Championship",
                    // "Ironman Los Cabos",
                    // "Ironman South Africa",
                    // "Ironman Australia",
                    // "Ironman 70.3 St. Croix",
                    // "Ironman Texas",
                    // "Ironman Lanzarote",
                    // "Ironman Brasil",
                    // "Ironman 70.3 Hawaii",
                    // "Ironman Cairns",
                    // "Ironman 70.3 Eagleman",
                    // "Ironman 70.3 Japan",
                    // "Ironman Austria",
                    // "Ironman Coeur d'Alene",
                    // "Ironman France",
                    // "Ironman European Championship",
                    // "Ironman UK",
                    // "Ironman Lake Placid",
                    // "Ironman Switzerland",
                    // "Ironman Canada",
                    // "Ironman Colorado",
                    // "Ironman Sweden",
                    // "Ironman North American Championship",
                    // "Ironman 70.3 European Championship",
                    // "Ironman Copenhagen",
                    // "Ironman Louisville",
                    // "Ironman Japan",
                    // "Ironman Wisconsin",
                    // "Ironman Wales",
                    // "Ironman Lake Tahoe",
                    // "Ironman Mallorca",
                    // "Ironman Malaysia",
                    // "Ironman Chattanooga",
                    // "Ironman World Championships",
                    // "Ironman Brazil",
                    // "Ironman 70.3 Asia Pacific Championnship"
                ];


exports.raceNames = raceNames;
