module.exports = [
     "Ironman Florida",
     "Ironman Arizona",
     "Ironman Cozumel",
     "Ironman Western Australia",
     "Ironman New Zealand",
     "Ironman South Africa",
     "Ironman Australia",
     "Ironman Lake Tahoe",
     "Ironman World Championships",
     "Ironman Malaysia",
     "Ironman Wales",
     "Ironman Wisconsin",
     "Ironman Japan",
     "Ironman Louisville",
     "Ironman Copenhagen",
     "Ironman North American Championships",
     "Ironman Sweden",
     "Ironman Canada",
     "Ironman Switzerland",
     "Ironman Lake Placid",
     "Ironman UK",
     "Ironman France",
     "Ironman European Championships",
     "Ironman Coeur d Alene",
     "Ironman Austria",
     "Ironman Cairns",
     "Ironman Florianopolis",
     "Ironman Lanzarote",
     "Ironman Texas",
     "Ironman Los Cabos",
     "Ironman Asia Pacific Championships",
     "Ironman Brasil",
     "Ironman Colorado"
];
