module.exports = [
    "Ironman St. Croix 70.3",
    "Ironman 70.3 Asia Pacific Championships",
    "Ironman 70.3 Japan",
    "Ironman 70.3 Eagleman",
    "Ironman 70.3 Hawaii",
    "Ironman 70.3 European Championships",
    "Ironman Asia Pacific Championships",
    "Ironman 70.3 California",
    "Ironman 70.3 Texas",
    "Ironman 70.3 Puerto Rico",
    "Ironman 70.3 New Orleans",
    "Ironman 70.3 Florida",
    "Ironman 70.3 St. George",
    "Ironman 70.3 Busselton",
    "Ironman 70.3 Mallorca",
    "Ironman 70.3 Aix en Provence",
    "Ironman 70.3 St. Polten",
    "Ironman 70.3 Rapperswil-Jona",
    "Ironman 70.3 Raleigh",
    "Ironman 70.3 Italy",
    "Ironman 70.3 Boise",
    "Ironman 70.3 Cairns",
    "Ironman 70.3 Kansas",
    "Ironman 70.3 UK",
    "Ironman 70.3 Boulder",
    "Ironman 70.3 Luxembourg",
    "Ironman 70.3 Mont Tremblant",
    "Ironman 70.3 Syracuse",
    "Ironman 70.3 Buffalo Springs Lake",
    "Ironman 70.3 Norway",
    "Ironman 70.3 Muncie",
    "Ironman 70.3 Berlin",
    "Ironman 70.3 Vineman",
]
