module.exports = [
    "Ironman St. Croix 70.3",
    "Ironman 70.3 Asia Pacific Championships",
    "Ironman 70.3 Japan",
    "Ironman 70.3 Eagleman",
    "Ironman 70.3 Hawaii",
    "Ironman 70.3 European Championships",
    "Ironman Asia Pacific Championships",
    "Ironman 70.3 California",
    "Ironman 70.3 Texas",
    "Ironman 70.3 Puerto Rico",
    "Ironman 70.3 New Orleans",
    "Ironman 70.3 Florida",
    "Ironman 70.3 St. George",
    "Ironman 70.3 Busselton",
    "Ironman 70.3 Mallorca",
    "Ironman 70.3 Aix en Provence",
    "Ironman 70.3 St. Polten",
    "Ironman 70.3 Rapperswil-Jona",
    "Ironman 70.3 Raleigh",
    "Ironman 70.3 Italy",
    "Ironman 70.3 Boise",
    "Ironman 70.3 Cairns",
    "Ironman 70.3 Kansas",
    "Ironman 70.3 UK",
    "Ironman 70.3 Boulder",
    "Ironman 70.3 Luxembourg",
    "Ironman 70.3 Mont Tremblant",
    "Ironman 70.3 Syracuse",
    "Ironman 70.3 Buffalo Springs Lake",
    "Ironman 70.3 Norway",
    "Ironman 70.3 Muncie",
    "Ironman 70.3 Berlin",
    "Ironman 70.3 Vineman",
    "Ironman 70.3 Racine",
    "Ironman 70.3 Calgary",
    "Ironman 70.3 Philippines",
    "Ironman 70.3 Wiesbaden",
    "Ironman 70.3 Steelhead",
    "Ironman 70.3 Timberman",
    "Ironman 70.3 Lake Stevens",
    "Ironman 70.3 Zell am See-Kaprun",
    "Ironman 70.3 Muskoka",
    "Ironman 70.3 Sunshine Coast",
    "Ironman 70.3 Lanzarote",
    "Ironman 70.3 Cozumel",
    "Ironman 70.3 Augusta",
    "Ironman 70.3 Port Macquarie",
    "Ironman 70.3 Austin",
    "Ironman 70.3 Miami",
    "Ironman 70.3 Mandurah",
    "Ironman 70.3 Pucon",
    "Ironman 70.3 Auckland",
    "Ironman 70.3 South Africa",
    "Ironman 70.3 Geelong",
    "Ironman 70.3 Panama",
    "Ironman 70.3 Putrajaya",
    "Ironman 70.3 Brasilia",
    "Ironman 70.3 Victoria"
]
